version: "3"
services:
  front:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front/src:/app/src
    command: npm run serve
  back:
    build: ./back
    ports:
      - "8082:3000"
    volumes:
      - ./back/src:/app/src
    command: npm run serve
