version: "2"
services:
  front:
    build: ./front
    ports:
      - "8080:8080"
    volumes:
      - ./front/src:/app/src
  back:
    build: ./back
    ports:
      - "8082:3000"
    volumes:
      - ./back/src:/app/src
